name: Hello SPIDY BRO Action

on: [push]  # Runs the action on every push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "Hello, SPIDY BRO! 🎉 Your GitHub Action is working!"
